version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-ny-bot
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://tg-ny-backend:8011
    restart: unless-stopped
    volumes:
      - ./data:/app/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: tg-ny-backend
    env_file:
      - .env
    environment:
      - BACKEND_PORT=8011
    ports:
      - "8011:8011"
    restart: unless-stopped
    volumes:
      - ./data:/app/data

